version: "2"
services:
  django-test:
    container_name: django_test
    build:
      context: .
      dockerfile: test.Dockerfile
    image: django_image_test
    stdin_open: true
    volumes:
      - ./code:/app
    ports:
      - "8080:8080"
