# Generated by Django 3.1.1 on 2020-09-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', 'update_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.TextField(default='bbc1ca1f-9f31-4c59-9c12-6af7f3c4b2eb'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sender',
            name='is_forward',
            field=models.BooleanField(default=False),
        ),
    ]
