# Generated by Django 3.1.1 on 2020-09-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_auto_20200923_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sender',
        ),
    ]
