# Generated by Django 3.1.1 on 2020-11-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
