# Generated by Django 3.1.1 on 2020-11-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_failed_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_password',
            field=models.CharField(default='lol', max_length=128, verbose_name='email_password'),
            preserve_default=False,
        ),
    ]
